# Generated by Django 3.2 on 2021-05-06 05:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_post_creator'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='post',
            new_name='content',
        ),
    ]
